site:
  title: MAARIF HAQUE
  jobtitle: Product/Experience designer, strategist
  description: Product/Experience designer, strategist. Specializing in designing 1-10 products focusing on MVP, growth, scalability, and continuous refinement through active user testing.
  image: ../og-image.png  
  author: S Maarif Haque
  email: reach.maarif@gmail.com
  linkedinUrl: https://linkedin.com/in/@maarifhaque

  navigationMain:
    - label: ABOUT
      href: /about
    - label: WORK
      href: /#work